# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pomodoro.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pomodoro_timer(object):
    def setupUi(self, pomodoro_timer):
        pomodoro_timer.setObjectName("pomodoro_timer")
        pomodoro_timer.resize(262, 210)
        self.verticalLayoutWidget = QtWidgets.QWidget(pomodoro_timer)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 261, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.horizontalLayoutWidget = QtWidgets.QWidget(pomodoro_timer)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 139, 221, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.start.setObjectName("start")
        self.horizontalLayout.addWidget(self.start)
        self.reset = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.reset.setObjectName("reset")
        self.horizontalLayout.addWidget(self.reset)
        self.gridLayoutWidget = QtWidgets.QWidget(pomodoro_timer)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 80, 261, 61))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.timer = QtWidgets.QLabel(self.gridLayoutWidget)
        self.timer.setObjectName("timer")
        self.gridLayout.addWidget(self.timer, 0, 0, 1, 1)

        self.retranslateUi(pomodoro_timer)
        self.start.clicked.connect(self.timer.update)
        QtCore.QMetaObject.connectSlotsByName(pomodoro_timer)

    def retranslateUi(self, pomodoro_timer):
        _translate = QtCore.QCoreApplication.translate
        pomodoro_timer.setWindowTitle(_translate("pomodoro_timer", "Form"))
        self.title.setText(_translate("pomodoro_timer", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Pomodoro Timer</span></p></body></html>"))
        self.start.setText(_translate("pomodoro_timer", "Start"))
        self.reset.setText(_translate("pomodoro_timer", "Reset"))
        self.timer.setText(_translate("pomodoro_timer", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">00:00</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pomodoro_timer = QtWidgets.QWidget()
    ui = Ui_pomodoro_timer()
    ui.setupUi(pomodoro_timer)
    pomodoro_timer.show()
    sys.exit(app.exec_())
